### ISSUE TITLE
firebase v9 breaks this tutorial

### ISSUE THREAD

**Issue by kratsg** [matthewmaribojoc/vue-firebase-auth#1]
Just reporting briefly, but it seems like the latest version of firebase changes things enough that one needs to rethink how to incorporate firebase into vue.

```
[plugin:vite:import-analysis] Failed to resolve entry for package "firebase". The package may have incorrect main/module/exports specified in its package.json: Missing "." export in "firebase" package
```

![Screen Shot 2021-09-01 at 10 46 20 AM](https://user-images.githubusercontent.com/761483/131719027-7e6501b6-752f-4050-b8d3-5f715bd77350.png)

This occurs when trying to get firebase included via `import firebase from 'firebase'`.

**Comment by kratsg** [comment]
The correct variation appears to be

```
import { initializeApp } from 'firebase/app';

// TODO: Replace the following with your app's Firebase project configuration
const firebaseConfig = {
  //...
};

const app = initializeApp(firebaseConfig);
```

but it won't show up during the set up which means having to create a lot of instances to pass around (probably has to do with the composition API on some level).

**Comment by Landstein** [comment]
I am still experiencing this issue.  Have there been any updates to resolve it?

**Comment by nuwanc** [comment]
made pull request for firebase v9 update
#2
